cache_dir: ./data/


comm:

  ann_list: 原神公告
  ann_detail: 原神公告#
  sub_ann: 订阅原神公告
  unsub_ann: 取消订阅原神公告

  material: 收集材料#
  show_material: 查看材料#

setting:
  # ------------ 原神公告设置 ------------
  # 屏蔽id
  ann_block:
    - 762
    - 422
    - 423
    - 1263
    - 495
    - 1957
  # 是否开启原神公告推送
  ann_cron_enable: true
  # 是否只允许非群员开启
  ann_enable_only_admin: true
  # 是否默认开启
  ann_group_default_enable: false
  # 刷新获取时间 单位分钟
  ann_cron_time: 20